### ISSUE TITLE
Missing Info.plist key

### ISSUE THREAD

**Issue by pedrosimao** [myflashlab/PermissionCheck-ANE#14]
While trying to send my App to AppStore, using Application Loader, I received the following message:

> Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSContactsUsageDescription key with a string value explaining to the user how the app uses this data.
> 
> Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data.

And that's weird because my app doesn't use Contacts or Calendar features. I guessed that might be a problem coming from you ANE. Do you think there is any chance that might be the case?

**Comment by pedrosimao** [comment]
Just for a reference, on my side I am using this code as InfoAdditions:

```
		<InfoAdditions>
			<![CDATA[
            <key>MinimumOSVersion</key>
            <string>10.0</string>
            <key>UIFileSharingEnabled</key><true/>
            <key>UIDeviceFamily</key>
            <array>
                <!-- iPad devices -->
                <string>2</string>
            </array>
            <key>UIRequiresPersistentWiFi</key>
            <string>YES</string>
            <key>NSMicrophoneUsageDescription</key>
	        <string>Your microphone will be used to record and listen to your voice.</string>
	        <key>NSSpeechRecognitionUsageDescription</key>
	        <string>Speech recognition will be used to determine which words you speak into this device's microphone.</string>
            ]]>
		</InfoAdditions>
```

**Comment by pedrosimao** [comment]
I was searching for more information on the internet and I found more people using your ANE are having the same problem with the last AIR SDK. Here is the link:

https://forums.adobe.com/thread/2277214

So, I think the problem really come from you. Let me know if you find out something.
Regards,

**Comment by myflashlab** [comment]
The ANE does have the required code for asking for contacts/etc permissions and it seems like new AIR SDK and iOS 10 are seeing these codes even if you are not using them in your project. We may need to do some more investigation on this but the current workaround is probably to use the ```NSContactsUsageDescription```, ```NSCalendarsUsageDescription``` key/values.

**Comment by pedrosimao** [comment]
That's what I have done. I have just sent my app to Apple for review. I hope they won't see it as a problem.

**Comment by myflashlab** [comment]
Keep us updated about how it goes please. Thanks.

**Comment by marzsman** [comment]
I had the exact same problem. 
After I added those 2 plist keys I got this error:

Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode 8 does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.

**Comment by myflashlab** [comment]
Sorry @marzsman , but it seems like your issue is not related to permissions. Asking for permissions is not really related to the ```Entitlement``` tag. If you want to use push notification, you should checkout our [FCM ANE](http://www.myflashlabs.com/product/fcm-firebase-air-native-extension/).

@pedrosimao So, how did it go? should we close the ticket and consider this a doable/reliable workaround?

**Comment by pedrosimao** [comment]
@myflashlab The app got accepted by Apple. So, the workaround works fine. But it would be nice if we can keep track of this issue, and have it solved when it will be possible.

**Comment by myflashlab** [comment]
Ok, it seems like the workaround is the way to go and people on other multi-platform software are also having the same problem. This post is explaining the reason in details: *Any where it says ```Cordova```, change it to ```AIR```.  https://stackoverflow.com/a/45207458/247658

> Since iOS 10 it is compulsary to have a usage description in the .plist if your app is requesting the related functionality (see here).
Therefore many plugins now include these keys in one form or another, including some of the plugins in your list. For example cordova-plugin-camera enables NSCameraUsageDescription to be specified via a plugin variable and cordova-diagnostic-plugin sets default placeholders for many of these including NSMotionUsageDescription.
However, having these keys in your .plist doesn't mean the messages they contain will automatically appear to users as permission requests. They will only be displayed when you call the relevant native iOS method via a plugin. For example, in the case of NSMotionUsageDescription, the message contained within will only be displayed if you call the diagnostic plugin function requestAndCheckMotionAuthorization().
App Store rejection occurs when an iOS app contains native calls to use functionality which requires a UsageDescription, but no such usage description key exists in the plist. For example, in the case of NSMotionUsageDescription, if your app contained a call to the native function CMMotionActivityManager.startActivityUpdatesToQueue but didn't contain NSMotionUsageDescription in the plist, your app would be rejected on uploading the binary to iTunes Connect. I assume Apple uses some software which scans your app binary on upload to check for calls to the relevant API functions and that corresponding UsageDescription plist entries are present.
In the case of a native iOS app, you would simply remove (or not add) calls to API functions that your weren't using, i.e. you wouldn't include a call to CMMotionActivityManager.startActivityUpdatesToQueue if your app didn't need to track motion.
However, in the case of a Cordova app, you are one step removed from the native code, which is included by installing plugins. For example, if you install cordova-diagnostic-plugin into your Cordova project, your app will contain a call to CMMotionActivityManager.startActivityUpdatesToQueue because that is in the plugin code. It doesn't matter if your app actually calls the plugin API function which in turn calls that native function, the fact is it's present in your app's code. And therefore NSMotionUsageDescription must be present in the .plist to prevent App Store rejection, hence why cordova-diagnostic-plugin adds a placeholder message for that key. But, as mentioned above, that permission request won't be present to the user unless you call requestAndCheckMotionAuthorization().

**Comment by jkpatel1463** [comment]
I face this issues.

**Comment by Elegarret** [comment]
@marzsman +1

After I submited my app to itunes connect via apploader I received letter from apple about "Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service..."
It appeared after I included facebook.ane. My app doesn't use pushes at all, but for some reason apple think it does..

**Comment by myflashlab** [comment]
@Elegarret and @marzsman The warning about the push notification cannot be related to the permissionsCheckANE, but it is very likely to be related to the overrideAir ANE. The root of the problem though is the very same thing that happens with iOS10+ and the current workaround is just similar to how we have described here in this post. However, considering that this problem is with the push notification warning, we kindly suggest you to share with us your experience with this on this page: https://github.com/myflashlab/common-dependencies-ANE/issues/13

@jkpatel1463 Which one?! if it's related to the permission check, we have already mentioned the workaround. on the other hand, if it is related to the push notification, the work around is explained [here](https://github.com/myflashlab/common-dependencies-ANE/issues/13).

**Comment by jkpatel1463** [comment]
@myflashlab 

I am using below list of ANE from myflashlab in my projects. I don't know exactly which ANE causes the issues:
1. videoPlayerSurface (com.myflashlab.air.extensions.videoPlayerSurface) 
2. permissionCheck (com.myflashlab.air.extensions.permissionCheck)
3. overrideAir (com.myflashlab.air.extensions.dependency.overrideAir)
4. androidSupport (com.myflashlab.air.extensions.dependency.androidSupport)

**Comment by myflashlab** [comment]
@jkpatel1463 As said in my last post:

> if it's related to the permission check, we have already mentioned the workaround. on the other hand, if it is related to the push notification, the work around is explained here.

Let me know if you have more question or anything is still unclear?

**Comment by myflashlab** [comment]
**NOTICE:** If you need MyFlashLabs developers' professional help, you should be either a [club member](https://www.myflashlabs.com/product/myflashlabs-club-membership/) or have a [premium support package](https://www.myflashlabs.com/product/myflashlabs-support/).
